/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swe.filetransfer.client;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author foysalmac
 */
public class ClientInitialView extends javax.swing.JFrame {

    /**
     * Creates new form ClientInitialView
     */
    public ClientInitialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientApplication = new javax.swing.JLabel();
        hostAddressTxt = new javax.swing.JTextField();
        HostAddress = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        portNumberTxt = new javax.swing.JTextField();
        selectClientDirectoryButton = new javax.swing.JButton();
        selectFileDirectoryTxt = new javax.swing.JTextField();
        startClientButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientApplication.setBackground(new java.awt.Color(51, 204, 255));
        clientApplication.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        clientApplication.setForeground(new java.awt.Color(0, 0, 204));
        clientApplication.setText("Client Application");

        hostAddressTxt.setText("127.0.0.1");
        hostAddressTxt.setBorder(null);
        hostAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostAddressTxtActionPerformed(evt);
            }
        });

        HostAddress.setBackground(new java.awt.Color(0, 204, 204));
        HostAddress.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        HostAddress.setText("Host Address");

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        jLabel2.setText("Port Number");

        portNumberTxt.setText("9090");
        portNumberTxt.setBorder(null);
        portNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberTxtActionPerformed(evt);
            }
        });

        selectClientDirectoryButton.setBackground(new java.awt.Color(204, 204, 204));
        selectClientDirectoryButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        selectClientDirectoryButton.setForeground(new java.awt.Color(0, 153, 153));
        selectClientDirectoryButton.setText("Select Client Directory");
        selectClientDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClientDirectoryButton_fileActionPerformed(evt);
            }
        });

        selectFileDirectoryTxt.setText("/Users/foysalmac/Desktop/client1");
        selectFileDirectoryTxt.setBorder(null);
        selectFileDirectoryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileDirectoryTxtActionPerformed(evt);
            }
        });

        startClientButton.setBackground(new java.awt.Color(51, 153, 0));
        startClientButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        startClientButton.setForeground(new java.awt.Color(204, 204, 204));
        startClientButton.setLabel("Start Client");
        startClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClientButtonstartClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(portNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectClientDirectoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(selectFileDirectoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(HostAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hostAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(clientApplication))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(startClientButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(clientApplication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HostAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(portNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileDirectoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectClientDirectoryButton))
                .addGap(32, 32, 32)
                .addComponent(startClientButton)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hostAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostAddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostAddressTxtActionPerformed

    private void portNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNumberTxtActionPerformed

    private void selectClientDirectoryButton_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClientDirectoryButton_fileActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                File f = chooser.getCurrentDirectory();
                String fileName= f.getAbsolutePath();
                selectFileDirectoryTxt.setText(fileName);
    }//GEN-LAST:event_selectClientDirectoryButton_fileActionPerformed

    private void selectFileDirectoryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileDirectoryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFileDirectoryTxtActionPerformed

    private void startClientButtonstartClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startClientButtonstartClientActionPerformed
        // TODO add your handling code here:
        System.out.println("Client start button pressed");
        String dir = selectFileDirectoryTxt.getText().trim();
        String hostAddress = hostAddressTxt.getText().trim();
        String portString = portNumberTxt.getText().trim();
        int port = Integer.parseInt(portString);
        dispose();
        try {
            new MainClientView(dir,hostAddress,port).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ClientInitialView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startClientButtonstartClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInitialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HostAddress;
    private javax.swing.JLabel clientApplication;
    private javax.swing.JTextField hostAddressTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField portNumberTxt;
    private javax.swing.JButton selectClientDirectoryButton;
    private javax.swing.JTextField selectFileDirectoryTxt;
    private javax.swing.JButton startClientButton;
    // End of variables declaration//GEN-END:variables
}
