/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swe.filetransfer.server;

/**
 *
 * @author foysalmac
 */
public class MainServerView extends javax.swing.JFrame {

    /**
     * Creates new form MainServerView
     */
    String dir;
    String port;
    public MainServerView() {
        initComponents();
    }
     public MainServerView(String dir,String port) {
        initComponents();
        this.dir=dir;
        this.port=port;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServerApplication = new javax.swing.JLabel();
        hostIpAddress = new javax.swing.JLabel();
        portNumber = new javax.swing.JLabel();
        serverDirectory = new javax.swing.JLabel();
        stopServerButton = new javax.swing.JButton();
        restartServerButton1 = new javax.swing.JButton();
        jListServer = new javax.swing.JList<>();
        jLabelserver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ServerApplication.setBackground(new java.awt.Color(51, 204, 255));
        ServerApplication.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ServerApplication.setForeground(new java.awt.Color(0, 0, 204));
        ServerApplication.setText("Server Application");

        hostIpAddress.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        hostIpAddress.setText("Host  Address");

        portNumber.setBackground(new java.awt.Color(0, 204, 204));
        portNumber.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        portNumber.setText("Port Number");

        serverDirectory.setBackground(new java.awt.Color(0, 204, 204));
        serverDirectory.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        serverDirectory.setText("Server Directory");

        stopServerButton.setBackground(new java.awt.Color(255, 51, 51));
        stopServerButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        stopServerButton.setForeground(new java.awt.Color(204, 204, 204));
        stopServerButton.setText("Stop ");
        stopServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopServerButtonstartClientActionPerformed(evt);
            }
        });

        restartServerButton1.setBackground(new java.awt.Color(51, 153, 0));
        restartServerButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        restartServerButton1.setForeground(new java.awt.Color(204, 204, 204));
        restartServerButton1.setText("Restart");
        restartServerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartServerButton1startClientActionPerformed(evt);
            }
        });

        jListServer.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListServerMouseEvent(evt);
            }
        });

        jLabelserver.setFont(new java.awt.Font("Mshtakan", 1, 14)); // NOI18N
        jLabelserver.setText("Server file list");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(restartServerButton1)
                        .addGap(31, 31, 31)
                        .addComponent(stopServerButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostIpAddress)
                            .addComponent(portNumber)
                            .addComponent(serverDirectory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jListServer, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(ServerApplication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabelserver)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ServerApplication)
                        .addGap(50, 50, 50)
                        .addComponent(hostIpAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(portNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverDirectory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelserver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jListServer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restartServerButton1)
                    .addComponent(stopServerButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopServerButtonstartClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopServerButtonstartClientActionPerformed
      
    }//GEN-LAST:event_stopServerButtonstartClientActionPerformed

    private void restartServerButton1startClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartServerButton1startClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restartServerButton1startClientActionPerformed

    private void jListServerMouseEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListServerMouseEvent
        // TODO add your handling code here:
        String selectedItem = (String) jListServer.getSelectedValue();
       // serverFileNameTxt.setText(selectedItem);
    }//GEN-LAST:event_jListServerMouseEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainServerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ServerApplication;
    private javax.swing.JLabel hostIpAddress;
    private javax.swing.JLabel jLabelserver;
    private javax.swing.JList<String> jListServer;
    private javax.swing.JLabel portNumber;
    private javax.swing.JButton restartServerButton1;
    private javax.swing.JLabel serverDirectory;
    private javax.swing.JButton stopServerButton;
    // End of variables declaration//GEN-END:variables
}
