/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swe.filetransfer.server;

import com.swe.filetransfer.client.*;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author foysalmac
 */
public class ServerInitialView extends javax.swing.JFrame {

    /**
     * Creates new form ClientInitialView
     */
    public ServerInitialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServerApplication = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        portNumberTxt = new javax.swing.JTextField();
        selectServerDirectoryButton = new javax.swing.JButton();
        selectFileDirectoryTxt = new javax.swing.JTextField();
        startServerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ServerApplication.setBackground(new java.awt.Color(51, 204, 255));
        ServerApplication.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ServerApplication.setForeground(new java.awt.Color(0, 0, 204));
        ServerApplication.setText("Server Application");

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        jLabel2.setText("Port Number");

        portNumberTxt.setText("9090");
        portNumberTxt.setBorder(null);
        portNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberTxtActionPerformed(evt);
            }
        });

        selectServerDirectoryButton.setBackground(new java.awt.Color(204, 204, 204));
        selectServerDirectoryButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        selectServerDirectoryButton.setForeground(new java.awt.Color(0, 153, 153));
        selectServerDirectoryButton.setText("Select Server Directory");
        selectServerDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectServerDirectoryButton_fileActionPerformed(evt);
            }
        });

        selectFileDirectoryTxt.setText("/Users/foysalmac/Desktop/server");
        selectFileDirectoryTxt.setBorder(null);
        selectFileDirectoryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileDirectoryTxtActionPerformed(evt);
            }
        });

        startServerButton.setBackground(new java.awt.Color(51, 153, 0));
        startServerButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        startServerButton.setForeground(new java.awt.Color(204, 204, 204));
        startServerButton.setText("Start Server");
        startServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerButtonstartClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(portNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectServerDirectoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(selectFileDirectoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(ServerApplication))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(startServerButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ServerApplication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(portNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileDirectoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectServerDirectoryButton))
                .addGap(32, 32, 32)
                .addComponent(startServerButton)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void portNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNumberTxtActionPerformed

    private void selectServerDirectoryButton_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectServerDirectoryButton_fileActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                File f = chooser.getCurrentDirectory();
                String fileName= f.getAbsolutePath();
                selectFileDirectoryTxt.setText(fileName);
    }//GEN-LAST:event_selectServerDirectoryButton_fileActionPerformed

    private void selectFileDirectoryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileDirectoryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFileDirectoryTxtActionPerformed

    private void startServerButtonstartClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerButtonstartClientActionPerformed
        // TODO add your handling code here:
        System.out.println("Client start button pressed");
        String dir = selectFileDirectoryTxt.getText().trim();
     
        String port = portNumberTxt.getText().trim();
        dispose();
        try {
            new MainServerView(dir,port).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ServerInitialView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startServerButtonstartClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerInitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerInitialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ServerApplication;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField portNumberTxt;
    private javax.swing.JTextField selectFileDirectoryTxt;
    private javax.swing.JButton selectServerDirectoryButton;
    private javax.swing.JButton startServerButton;
    // End of variables declaration//GEN-END:variables
}
